--- 
/Review: 
  getProductId: 
    startId: 
    productId: 
      autocomplete: productId
    startDate: 
    page: 
    offset: 
  getBrandId: 
    startId: 
    startDate: 
    brandId: 
      autocomplete: brandId
/Favorite: 
  deleteFavoriteStock: 
    stockId: 
  getFavoritesForCustomer: 
    sortDirection: 
    page: 
    sort: 
    limit: 
    offset: 
/Points: 
  viewLoyaltyPoints: 
    customerId: 
    type: 
    t: 
/CreditCard: 
  getCreditCardById: 
    id: 
  deleteCreditCardById: 
    id: 
/Brand: 
  getCustomerId: 
    customerId: 
    collapse: 
    maxResults: 
  getId: 
    id:
      autocomplete: brandId
/ApiDeveloper: 
  getByApiKeyHash: 
    lookupKey: 
  getAll: 
    page: 
    sort: 
    orderBy: 
    limit: 
    sortAsc: 
  getByEmail: 
    email: 
/Search: 
  getGetFacetFields: 
    filterExpression: 
  getBatchSearch: 
    batch: 
  getGetSolrFieldNames: 
    filterExpression: 
  getSearch: 
    pageCount: 
    currentPage: 
    term: 
    page: 
    filters:
      type: jsonMap
      autocomplete: { facets: facetValues }
      force_array: true
    sort:
      type: jsonMap
      autocomplete: { sortBy: sortOrder }
    limit: 
    facets: 
      autocomplete: facets
/FavoriteSearch: 
  deleteFavoriteSearch: 
    name: 
    url: 
/AutoComplete: 
  getAutoComplete: 
    term: 
/Product: 
  getProductByStockId: 
    stockId: 
  getProductById: 
    id:
      autocomplete: productId
  getProductByUPC: 
    upc: 
  getProductByStyleId: 
    styleId:
      autocomplete: styleId
/Order: 
  getOrderByClaimTicketId: 
    claimTicketId: 
  getOrderById: 
    id: 
    type: 
  getOrdersForCustomer: 
    fromDate: 
    type: 
    range: 
    toDate: 
/Image: 
  GetStyleOrProductId: 
    styleId:
      autocomplete: styleId
    productId: 
      autocomplete: productId
    type: 
    recipe: 
  GetProductId: 
    productId: 
      autocomplete: productId
    type: 
    recipe: 
  GetStyleId: 
    styleId:
      autocomplete: styleId
    type: 
    recipe: 
/Compatibility: 
  getVersionInfo: 
    version: 
/Customer: 
  getCustomer: 
    access_token: 
/EventLogger: 
  logEvent: 
    name: 
/CoreValue: 
  getById: 
    id: 
/Badge/Feed: 
  getBadgeFeed: 
    t: 
/Address: 
  deleteAddress: 
    id: 
  getVerifiedIds: 
    list: 
  getAddressById: 
    id: 
/Cart: 
  bySessionId: 
    city: 
    address: 
    shippingTypeCode: 
    addressId: 
    postalCode: 
    sessionId: 
    state: 
/Statistics: 
  getKillSwitchStatus101: 
    killSwitchStatusZappos101: 
  getStatistics: 
    timespan: 
    location: 
    option: 
    startOrderItemId: 
    startDate: 
    type: 
      autocomplete: statisticsType
    filters: 
    limit: 
  getKillSwitchStatus102: 
    killSwitchStatusZappos102: 
/Search/Similarity: 
  getSimilaritySearch: 
    category: 
    styleId: 
      autocomplete: styleId
    productType: 
    page: 
    brandId: 
      autocomplete: brandId
    type: 
      autocomplete: similarityType
    emphasis:
      autocomplete: similarityEmphasis
    limit: 
    subCategory: 
/ApiApplication: 
  getById: 
    id: 
  removeAttribute: 
    id: 
    apiAttributeId: 
  getApiAttribute: 
    id: 
    apiAttributeId: 
/Cache: 
  getCacheById: 
    id: 
  clearCacheById: 
    id: 
/ApiAttribute: 
  getById: 
    id: 
  getByName: 
    name: 
  deleteAttribute: 
    id: 
